
dist: trusty

sudo: false

language: generic

branches:
    only:
        - master

addons:
    apt:
        packages:
            - doxygen
            - graphviz
            
script:
    - ./make_docs.sh