Berkeley YACC: byacc/error.c File Reference
error.c File Reference
#include "defs.h"
Functions
fatal (char *msg)
no_space ()
open_error (char *filename)
unexpected_EOF ()
print_pos (char *st_line, char *st_cptr)
syntax_error (int st_lineno, char *st_line, char *st_cptr)
unterminated_comment (int c_lineno, char *c_line, char *c_cptr)
unterminated_string (int s_lineno, char *s_line, char *s_cptr)
unterminated_text (int t_lineno, char *t_line, char *t_cptr)
unterminated_union (int u_lineno, char *u_line, char *u_cptr)
over_unionized (char *u_cptr)
illegal_tag (int t_lineno, char *t_line, char *t_cptr)
illegal_character (char *c_cptr)
used_reserved (char *s)
tokenized_start (char *s)
retyped_warning (char *s)
reprec_warning (char *s)
revalued_warning (char *s)
terminal_start (char *s)
restarted_warning ()
no_grammar ()
terminal_lhs (int s_lineno)
prec_redeclared ()
unterminated_action (int a_lineno, char *a_line, char *a_cptr)
dollar_warning (int a_lineno, int i)
dollar_error (int a_lineno, char *a_line, char *a_cptr)
untyped_lhs ()
untyped_rhs (int i, char *s)
unknown_rhs (int i)
default_action_warning ()
undefined_goal (char *s)
undefined_symbol_warning (char *s)
Function Documentation
default_action_warning ()
Definition at line 298 of file error.c.
References input_file_name, lineno, and myname.
Referenced by end_rule().
 {
     fprintf(stderr, "%s: w - line %d of \"%s\", the default action assigns an \
 undefined value to $$\n", myname, lineno, input_file_name);
 }
dollar_error (int a_lineno, char * a_line, char * a_cptr)
Definition at line 259 of file error.c.
References done(), input_file_name, myname, and print_pos().
Referenced by copy_action().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", illegal $-name\n",
         myname, a_lineno, input_file_name);
     print_pos(a_line, a_cptr);
     done(1);
 }
dollar_warning (int a_lineno, int i)
Definition at line 250 of file error.c.
References input_file_name, and myname.
Referenced by copy_action().
 {
     fprintf(stderr, "%s: w - line %d of \"%s\", $%d references beyond the \
 end of the current rule\n", myname, a_lineno, input_file_name, i);
 }
fatal (char * msg)
Definition at line 6 of file error.c.
References done(), and myname.
Referenced by new_state(), pack_vector(), and set_goto_map().
 {
     fprintf(stderr, "%s: f - %s\n", myname, msg);
     done(2);
 }
illegal_character (char * c_cptr)
Definition at line 146 of file error.c.
References done(), input_file_name, line, lineno, myname, and print_pos().
Referenced by get_literal().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", illegal character\n",
         myname, lineno, input_file_name);
     print_pos(line, c_cptr);
     done(1);
 }
illegal_tag (int t_lineno, char * t_line, char * t_cptr)
Definition at line 134 of file error.c.
References done(), input_file_name, myname, and print_pos().
Referenced by get_tag().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", illegal tag\n",
         myname, t_lineno, input_file_name);
     print_pos(t_line, t_cptr);
     done(1);
 }
no_grammar ()
Definition at line 214 of file error.c.
References done(), input_file_name, lineno, and myname.
Referenced by advance_to_start().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", no grammar has been \
 specified\n", myname, lineno, input_file_name);
     done(1);
 }
no_space ()
Definition at line 14 of file error.c.
References done(), and myname.
Referenced by allocate(), cachec(), create_file_names(), create_symbol_table(), dup_line(), expand_items(), expand_rules(), get_line(), get_literal(), get_tag(), initialize_grammar(), initialize_states(), make_bucket(), output_debug(), pack_grammar(), pack_names(), pack_symbols(), pack_vector(), read_declarations(), set_nullable(), unused_rules(), and verbose().
 {
     fprintf(stderr, "%s: f - out of space\n", myname);
     done(2);
 }
open_error (char * filename)
Definition at line 21 of file error.c.
References done(), and myname.
Referenced by open_files(), output_defines(), output_semantic_actions(), and output_stored_text().
 {
     fprintf(stderr, "%s: f - cannot open \"%s\"\n", myname, filename);
     done(2);
 }
over_unionized (char * u_cptr)
Definition at line 124 of file error.c.
References done(), input_file_name, line, lineno, myname, and print_pos().
Referenced by copy_union().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", too many %%union \
 declarations\n", myname, lineno, input_file_name);
     print_pos(line, u_cptr);
     done(1);
 }
prec_redeclared ()
Definition at line 231 of file error.c.
References input_file_name, lineno, and myname.
Referenced by mark_symbol().
 {
     fprintf(stderr, "%s: w - line %d of  \"%s\", conflicting %%prec \
 specifiers\n", myname, lineno, input_file_name);
 }
print_pos (char * st_line, char * st_cptr)
Definition at line 37 of file error.c.
Referenced by dollar_error(), illegal_character(), illegal_tag(), over_unionized(), syntax_error(), unterminated_action(), unterminated_comment(), unterminated_string(), unterminated_text(), and unterminated_union().
 {
     register char *s;
     if (st_line == 0) return;
     for (s = st_line; *s != '\n'; ++s)
     {
     if (isprint(*s) || *s == '\t')
         putc(*s, stderr);
     else
         putc('?', stderr);
     }
     putc('\n', stderr);
     for (s = st_line; s < st_cptr; ++s)
     {
     if (*s == '\t')
         putc('\t', stderr);
     else
         putc(' ', stderr);
     }
     putc('^', stderr);
     putc('\n', stderr);
 }
reprec_warning (char * s)
Definition at line 182 of file error.c.
References input_file_name, lineno, and myname.
Referenced by declare_tokens().
 {
     fprintf(stderr, "%s: w - line %d of \"%s\", the precedence of %s has been \
 redeclared\n", myname, lineno, input_file_name, s);
 }
restarted_warning ()
Definition at line 207 of file error.c.
References input_file_name, lineno, and myname.
Referenced by declare_start().
 {
     fprintf(stderr, "%s: w - line %d of \"%s\", the start symbol has been \
 redeclared\n", myname, lineno, input_file_name);
 }
retyped_warning (char * s)
Definition at line 174 of file error.c.
References input_file_name, lineno, and myname.
Referenced by declare_tokens(), and declare_types().
 {
     fprintf(stderr, "%s: w - line %d of \"%s\", the type of %s has been \
 redeclared\n", myname, lineno, input_file_name, s);
 }
revalued_warning (char * s)
Definition at line 190 of file error.c.
References input_file_name, lineno, and myname.
Referenced by declare_tokens().
 {
     fprintf(stderr, "%s: w - line %d of \"%s\", the value of %s has been \
 redeclared\n", myname, lineno, input_file_name, s);
 }
syntax_error (int st_lineno, char * st_line, char * st_cptr)
Definition at line 64 of file error.c.
References done(), input_file_name, myname, and print_pos().
Referenced by advance_to_start(), copy_ident(), declare_start(), declare_types(), keyword(), mark_symbol(), read_declarations(), and read_grammar().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", syntax error\n",
         myname, st_lineno, input_file_name);
     print_pos(st_line, st_cptr);
     done(1);
 }
terminal_lhs (int s_lineno)
Definition at line 222 of file error.c.
References done(), input_file_name, and myname.
Referenced by start_rule().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", a token appears on the lhs \
 of a production\n", myname, s_lineno, input_file_name);
     done(1);
 }
terminal_start (char * s)
Definition at line 198 of file error.c.
References done(), input_file_name, lineno, and myname.
Referenced by advance_to_start(), and declare_start().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", the start symbol %s is a \
 token\n", myname, lineno, input_file_name, s);
     done(1);
 }
tokenized_start (char * s)
Definition at line 165 of file error.c.
References done(), input_file_name, lineno, and myname.
Referenced by declare_tokens().
 {
      fprintf(stderr, "%s: e - line %d of \"%s\", the start symbol %s cannot be \
 declared to be a token\n", myname, lineno, input_file_name, s);
      done(1);
 }
undefined_goal (char * s)
Definition at line 305 of file error.c.
References done(), and myname.
Referenced by check_symbols().
 {
     fprintf(stderr, "%s: e - the start symbol %s is undefined\n", myname, s);
     done(1);
 }
undefined_symbol_warning (char * s)
Definition at line 313 of file error.c.
References myname.
Referenced by check_symbols().
 {
     fprintf(stderr, "%s: w - the symbol %s is undefined\n", myname, s);
 }
unexpected_EOF ()
Definition at line 29 of file error.c.
References done(), input_file_name, lineno, and myname.
Referenced by advance_to_start(), copy_ident(), declare_start(), declare_tokens(), declare_types(), get_tag(), and read_declarations().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", unexpected end-of-file\n",
         myname, lineno, input_file_name);
     done(1);
 }
unknown_rhs (int i)
Definition at line 289 of file error.c.
References done(), input_file_name, lineno, and myname.
Referenced by copy_action().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", $%d is untyped\n",
         myname, lineno, input_file_name, i);
     done(1);
 }
unterminated_action (int a_lineno, char * a_line, char * a_cptr)
Definition at line 238 of file error.c.
References done(), input_file_name, myname, and print_pos().
Referenced by copy_action().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", unterminated action\n",
         myname, a_lineno, input_file_name);
     print_pos(a_line, a_cptr);
     done(1);
 }
unterminated_comment (int c_lineno, char * c_line, char * c_cptr)
Definition at line 76 of file error.c.
References done(), input_file_name, myname, and print_pos().
Referenced by copy_action(), copy_text(), copy_union(), and skip_comment().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", unmatched /*\n",
         myname, c_lineno, input_file_name);
     print_pos(c_line, c_cptr);
     done(1);
 }
unterminated_string (int s_lineno, char * s_line, char * s_cptr)
Definition at line 88 of file error.c.
References done(), input_file_name, myname, and print_pos().
Referenced by copy_action(), copy_text(), copy_union(), and get_literal().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", unterminated string\n",
         myname, s_lineno, input_file_name);
     print_pos(s_line, s_cptr);
     done(1);
 }
unterminated_text (int t_lineno, char * t_line, char * t_cptr)
Definition at line 100 of file error.c.
References done(), input_file_name, myname, and print_pos().
Referenced by copy_text().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", unmatched %%{\n",
         myname, t_lineno, input_file_name);
     print_pos(t_line, t_cptr);
     done(1);
 }
unterminated_union (int u_lineno, char * u_line, char * u_cptr)
Definition at line 112 of file error.c.
References done(), input_file_name, myname, and print_pos().
Referenced by copy_union().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", unterminated %%union \
 declaration\n", myname, u_lineno, input_file_name);
     print_pos(u_line, u_cptr);
     done(1);
 }
untyped_lhs ()
Definition at line 271 of file error.c.
References done(), input_file_name, lineno, and myname.
Referenced by copy_action().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", $$ is untyped\n",
         myname, lineno, input_file_name);
     done(1);
 }
untyped_rhs (int i, char * s)
Definition at line 279 of file error.c.
References done(), input_file_name, lineno, and myname.
Referenced by copy_action().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", $%d (%s) is untyped\n",
         myname, lineno, input_file_name, i, s);
     done(1);
 }
used_reserved (char * s)
Definition at line 156 of file error.c.
References done(), input_file_name, lineno, and myname.
Referenced by get_name().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", illegal use of reserved symbol \
 %s\n", myname, lineno, input_file_name, s);
     done(1);
 }