Berkeley YACC: Memory optimization
Memory optimization
Functions to reduce the memory footprint.
Functions
pack_names ()
pack_symbols ()
pack_grammar ()
Detailed Description
Functions to reduce the memory footprint.
The functions in this module are used to pack the symbols manipulated by the program, switching from many small allocations to a few big memory chunks. This slightly reduces the memory footprint of the program, while also improving locality, thus incrementing the performance of the subsequent algorithms, which very often need to iterate on the data
Function Documentation
pack_grammar ()
Definition at line 1680 of file reader.c.
References bucket::assoc, FREE, bucket::index, MALLOC, nitems, no_space(), nrules, prec, bucket::prec, rassoc, REALLOC, ritem, rlhs, rprec, rrhs, start_symbol, TERM, TOKEN, and UNDEFINED.
Referenced by reader().
 {
     register int i, j;
     int assoc, prec;
     ritem = (short *) MALLOC(nitems*sizeof(short));
     if (ritem == 0) no_space();
     rlhs = (short *) MALLOC(nrules*sizeof(short));
     if (rlhs == 0) no_space();
     rrhs = (short *) MALLOC((nrules+1)*sizeof(short));
     if (rrhs == 0) no_space();
     rprec = (short *) REALLOC(rprec, nrules*sizeof(short));
     if (rprec == 0) no_space();
     rassoc = REALLOC(rassoc, nrules);
     if (rassoc == 0) no_space();
     ritem[0] = -1;
     ritem[1] = goal->index;
     ritem[2] = 0;
     ritem[3] = -2;
     rlhs[0] = 0;
     rlhs[1] = 0;
     rlhs[2] = start_symbol;
     rrhs[0] = 0;
     rrhs[1] = 0;
     rrhs[2] = 1;
     j = 4;
     for (i = 3; i < nrules; ++i)
     {
         rlhs[i] = plhs[i]->index;
         rrhs[i] = j;
         assoc = TOKEN;
         prec = 0;
         while (pitem[j])
         {
             ritem[j] = pitem[j]->index;
             if (pitem[j]->class == TERM)
             {
                 prec = pitem[j]->prec;
                 assoc = pitem[j]->assoc;
             }
             ++j;
         }
         ritem[j] = -i;
         ++j;
         if (rprec[i] == UNDEFINED)
         {
             rprec[i] = prec;
             rassoc[i] = assoc;
         }
     }
     rrhs[i] = j;
     FREE(plhs);
     FREE(pitem);
 }
pack_names ()
Definition at line 1507 of file reader.c.
References first_symbol, FREE, MALLOC, bucket::name, name_pool, name_pool_size, bucket::next, no_space(), and strcpy().
Referenced by reader().
 {
     register bucket *bp;
     register char *p, *s, *t;
     name_pool_size = 13;  /* 13 == sizeof("$end") + sizeof("$accept") */
     for (bp = first_symbol; bp; bp = bp->next)
         name_pool_size += strlen(bp->name) + 1;
     name_pool = MALLOC(name_pool_size);
     if (name_pool == 0) no_space();
     strcpy(name_pool, "$accept");
     strcpy(name_pool+8, "$end");
     t = name_pool + 13;
     for (bp = first_symbol; bp; bp = bp->next)
     {
         p = t;
         s = bp->name;
         while (*t++ = *s++) continue;
         FREE(bp->name);
         bp->name = p;
     }
 }
pack_symbols ()
Definition at line 1553 of file reader.c.
References bucket::assoc, bucket::class, first_symbol, FREE, bucket::index, MALLOC, bucket::name, name_pool, bucket::next, no_space(), nsyms, ntokens, nvars, bucket::prec, start_symbol, symbol_assoc, symbol_name, symbol_prec, symbol_value, TERM, TOKEN, UNDEFINED, shorts::value, and bucket::value.
Referenced by reader().
 {
     register bucket *bp;
     register bucket **v;
     register int i, j, k, n;
     nsyms = 2;
     ntokens = 1;
     for (bp = first_symbol; bp; bp = bp->next)
     {
         ++nsyms;
         if (bp->class == TERM) ++ntokens;
     }
     start_symbol = ntokens;
     nvars = nsyms - ntokens;
     symbol_name = (char **) MALLOC(nsyms*sizeof(char *));
     if (symbol_name == 0) no_space();
     symbol_value = (short *) MALLOC(nsyms*sizeof(short));
     if (symbol_value == 0) no_space();
     symbol_prec = (short *) MALLOC(nsyms*sizeof(short));
     if (symbol_prec == 0) no_space();
     symbol_assoc = MALLOC(nsyms);
     if (symbol_assoc == 0) no_space();
     v = (bucket **) MALLOC(nsyms*sizeof(bucket *));
     if (v == 0) no_space();
     v[0] = 0;
     v[start_symbol] = 0;
     i = 1;
     j = start_symbol + 1;
     for (bp = first_symbol; bp; bp = bp->next)
     {
         if (bp->class == TERM)
             v[i++] = bp;
         else
             v[j++] = bp;
     }
     assert(i == ntokens && j == nsyms);
     for (i = 1; i < ntokens; ++i)
         v[i]->index = i;
     goal->index = start_symbol + 1;
     k = start_symbol + 2;
     while (++i < nsyms)
         if (v[i] != goal)
         {
             v[i]->index = k;
             ++k;
         }
     goal->value = 0;
     k = 1;
     for (i = start_symbol + 1; i < nsyms; ++i)
     {
         if (v[i] != goal)
         {
             v[i]->value = k;
             ++k;
         }
     }
     k = 0;
     for (i = 1; i < ntokens; ++i)
     {
         n = v[i]->value;
         if (n > 256)
         {
             for (j = k++; j > 0 && symbol_value[j-1] > n; --j)
                 symbol_value[j] = symbol_value[j-1];
             symbol_value[j] = n;
         }
     }
     if (v[1]->value == UNDEFINED)
         v[1]->value = 256;
     j = 0;
     n = 257;
     for (i = 2; i < ntokens; ++i)
     {
         if (v[i]->value == UNDEFINED)
         {
             while (j < k && n == symbol_value[j])
             {
                 while (++j < k && n == symbol_value[j]) continue;
                 ++n;
             }
             v[i]->value = n;
             ++n;
         }
     }
     symbol_name[0] = name_pool + 8;
     symbol_value[0] = 0;
     symbol_prec[0] = 0;
     symbol_assoc[0] = TOKEN;
     for (i = 1; i < ntokens; ++i)
     {
         symbol_name[i] = v[i]->name;
         symbol_value[i] = v[i]->value;
         symbol_prec[i] = v[i]->prec;
         symbol_assoc[i] = v[i]->assoc;
     }
     symbol_name[start_symbol] = name_pool;
     symbol_value[start_symbol] = -1;
     symbol_prec[start_symbol] = 0;
     symbol_assoc[start_symbol] = TOKEN;
     for (++i; i < nsyms; ++i)
     {
         k = v[i]->index;
         symbol_name[k] = v[i]->name;
         symbol_value[k] = v[i]->value;
         symbol_prec[k] = v[i]->prec;
         symbol_assoc[k] = v[i]->assoc;
     }
     FREE(v);
 }