Berkeley YACC: Error handling
Error handling
Routines for handling errors and warnings and performing cleanup.
Files
file error.c
Routines to report various warnings and errors and maybe quit the program.
Functions
fatal (char *msg)
no_space ()
open_error (char *filename)
unexpected_EOF ()
print_pos (char *st_line, char *st_cptr)
syntax_error (int st_lineno, char *st_line, char *st_cptr)
unterminated_comment (int c_lineno, char *c_line, char *c_cptr)
unterminated_string (int s_lineno, char *s_line, char *s_cptr)
unterminated_text (int t_lineno, char *t_line, char *t_cptr)
unterminated_union (int u_lineno, char *u_line, char *u_cptr)
over_unionized (char *u_cptr)
illegal_tag (int t_lineno, char *t_line, char *t_cptr)
illegal_character (char *c_cptr)
used_reserved (char *s)
tokenized_start (char *s)
retyped_warning (char *s)
reprec_warning (char *s)
revalued_warning (char *s)
terminal_start (char *s)
restarted_warning ()
no_grammar ()
terminal_lhs (int s_lineno)
prec_redeclared ()
unterminated_action (int a_lineno, char *a_line, char *a_cptr)
dollar_warning (int a_lineno, int i)
dollar_error (int a_lineno, char *a_line, char *a_cptr)
untyped_lhs ()
untyped_rhs (int i, char *s)
unknown_rhs (int i)
default_action_warning ()
undefined_goal (char *s)
undefined_symbol_warning (char *s)
done (int k)
Shutdown function.
onintr ()
Signal handler callback.
set_signals ()
Sets the appropriate signal handlers up.
Detailed Description
Routines for handling errors and warnings and performing cleanup.
Function Documentation
default_action_warning ()
Definition at line 311 of file error.c.
References input_file_name, lineno, and myname.
Referenced by end_rule().
 {
     fprintf(stderr, "%s: w - line %d of \"%s\", the default action assigns an \
 undefined value to $$\n", myname, lineno, input_file_name);
 }
dollar_error (int a_lineno, char * a_line, char * a_cptr)
Definition at line 272 of file error.c.
References done(), input_file_name, myname, and print_pos().
Referenced by copy_action().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", illegal $-name\n",
             myname, a_lineno, input_file_name);
     print_pos(a_line, a_cptr);
     done(1);
 }
dollar_warning (int a_lineno, int i)
Definition at line 263 of file error.c.
References input_file_name, and myname.
Referenced by copy_action().
 {
     fprintf(stderr, "%s: w - line %d of \"%s\", $%d references beyond the \
 end of the current rule\n", myname, a_lineno, input_file_name, i);
 }
done (int k)
Shutdown function.
This function deletes all temporary files still open and exits the program with the status code passed to it.
Parameters
[in] k The status code the program should exit with
Definition at line 73 of file main.c.
References action_file, action_file_name, text_file, text_file_name, union_file, and union_file_name.
Referenced by build_relations(), dollar_error(), fatal(), illegal_character(), illegal_tag(), main(), no_grammar(), no_space(), onintr(), open_error(), over_unionized(), set_nullable(), syntax_error(), terminal_lhs(), terminal_start(), tokenized_start(), undefined_goal(), unexpected_EOF(), unknown_rhs(), unterminated_action(), unterminated_comment(), unterminated_string(), unterminated_text(), unterminated_union(), untyped_lhs(), untyped_rhs(), and used_reserved().
 {
     if (action_file) { fclose(action_file); unlink(action_file_name); }
     if (text_file) { fclose(text_file); unlink(text_file_name); }
     if (union_file) { fclose(union_file); unlink(union_file_name); }
     exit(k);
 }
fatal (char * msg)
Definition at line 19 of file error.c.
References done(), and myname.
Referenced by new_state(), pack_vector(), and set_goto_map().
 {
     fprintf(stderr, "%s: f - %s\n", myname, msg);
     done(2);
 }
illegal_character (char * c_cptr)
Definition at line 159 of file error.c.
References done(), input_file_name, line, lineno, myname, and print_pos().
Referenced by get_literal().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", illegal character\n",
             myname, lineno, input_file_name);
     print_pos(line, c_cptr);
     done(1);
 }
illegal_tag (int t_lineno, char * t_line, char * t_cptr)
Definition at line 147 of file error.c.
References done(), input_file_name, myname, and print_pos().
Referenced by get_tag().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", illegal tag\n",
             myname, t_lineno, input_file_name);
     print_pos(t_line, t_cptr);
     done(1);
 }
no_grammar ()
Definition at line 227 of file error.c.
References done(), input_file_name, lineno, and myname.
Referenced by advance_to_start().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", no grammar has been \
 specified\n", myname, lineno, input_file_name);
     done(1);
 }
no_space ()
Definition at line 27 of file error.c.
References done(), and myname.
Referenced by allocate(), cachec(), create_file_names(), create_symbol_table(), dup_line(), expand_items(), expand_rules(), get_line(), get_literal(), get_tag(), initialize_grammar(), initialize_states(), make_bucket(), output_debug(), pack_grammar(), pack_names(), pack_symbols(), pack_vector(), read_declarations(), set_nullable(), unused_rules(), and verbose().
 {
     fprintf(stderr, "%s: f - out of space\n", myname);
     done(2);
 }
onintr ()
Signal handler callback.
This function is executed whenever the program receives a shutdown signal (either SIGINT, SIGTERM, or SIGHUP). It just calls done(int) with code 1.
Definition at line 89 of file main.c.
References done().
Referenced by set_signals().
 {
     done(1);
 }
open_error (char * filename)
Definition at line 34 of file error.c.
References done(), and myname.
Referenced by open_files(), output_defines(), output_semantic_actions(), and output_stored_text().
 {
     fprintf(stderr, "%s: f - cannot open \"%s\"\n", myname, filename);
     done(2);
 }
over_unionized (char * u_cptr)
Definition at line 137 of file error.c.
References done(), input_file_name, line, lineno, myname, and print_pos().
Referenced by copy_union().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", too many %%union \
 declarations\n", myname, lineno, input_file_name);
     print_pos(line, u_cptr);
     done(1);
 }
prec_redeclared ()
Definition at line 244 of file error.c.
References input_file_name, lineno, and myname.
Referenced by mark_symbol().
 {
     fprintf(stderr, "%s: w - line %d of  \"%s\", conflicting %%prec \
 specifiers\n", myname, lineno, input_file_name);
 }
print_pos (char * st_line, char * st_cptr)
Definition at line 50 of file error.c.
Referenced by dollar_error(), illegal_character(), illegal_tag(), over_unionized(), syntax_error(), unterminated_action(), unterminated_comment(), unterminated_string(), unterminated_text(), and unterminated_union().
 {
     register char *s;
     if (st_line == 0) return;
     for (s = st_line; *s != '\n'; ++s)
     {
         if (isprint(*s) || *s == '\t')
             putc(*s, stderr);
         else
             putc('?', stderr);
     }
     putc('\n', stderr);
     for (s = st_line; s < st_cptr; ++s)
     {
         if (*s == '\t')
             putc('\t', stderr);
         else
             putc(' ', stderr);
     }
     putc('^', stderr);
     putc('\n', stderr);
 }
reprec_warning (char * s)
Definition at line 195 of file error.c.
References input_file_name, lineno, and myname.
Referenced by declare_tokens().
 {
     fprintf(stderr, "%s: w - line %d of \"%s\", the precedence of %s has been \
 redeclared\n", myname, lineno, input_file_name, s);
 }
restarted_warning ()
Definition at line 220 of file error.c.
References input_file_name, lineno, and myname.
Referenced by declare_start().
 {
     fprintf(stderr, "%s: w - line %d of \"%s\", the start symbol has been \
 redeclared\n", myname, lineno, input_file_name);
 }
retyped_warning (char * s)
Definition at line 187 of file error.c.
References input_file_name, lineno, and myname.
Referenced by declare_tokens(), and declare_types().
 {
     fprintf(stderr, "%s: w - line %d of \"%s\", the type of %s has been \
 redeclared\n", myname, lineno, input_file_name, s);
 }
revalued_warning (char * s)
Definition at line 203 of file error.c.
References input_file_name, lineno, and myname.
Referenced by declare_tokens().
 {
     fprintf(stderr, "%s: w - line %d of \"%s\", the value of %s has been \
 redeclared\n", myname, lineno, input_file_name, s);
 }
set_signals ()
Sets the appropriate signal handlers up.
This function is executed on startup and sets onintr() as callback for any shutdown signal (SIGINT, SIGTERM, SIGHUP).
Definition at line 102 of file main.c.
References onintr().
Referenced by main().
 {
 #ifdef SIGINT
     if (signal(SIGINT, SIG_IGN) != SIG_IGN)
         signal(SIGINT, onintr);
 #endif
 #ifdef SIGTERM
     if (signal(SIGTERM, SIG_IGN) != SIG_IGN)
         signal(SIGTERM, onintr);
 #endif
 #ifdef SIGHUP
     if (signal(SIGHUP, SIG_IGN) != SIG_IGN)
         signal(SIGHUP, onintr);
 #endif
 }
syntax_error (int st_lineno, char * st_line, char * st_cptr)
Definition at line 77 of file error.c.
References done(), input_file_name, myname, and print_pos().
Referenced by advance_to_start(), copy_ident(), declare_start(), declare_types(), keyword(), mark_symbol(), read_declarations(), and read_grammar().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", syntax error\n",
             myname, st_lineno, input_file_name);
     print_pos(st_line, st_cptr);
     done(1);
 }
terminal_lhs (int s_lineno)
Definition at line 235 of file error.c.
References done(), input_file_name, and myname.
Referenced by start_rule().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", a token appears on the lhs \
 of a production\n", myname, s_lineno, input_file_name);
     done(1);
 }
terminal_start (char * s)
Definition at line 211 of file error.c.
References done(), input_file_name, lineno, and myname.
Referenced by advance_to_start(), and declare_start().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", the start symbol %s is a \
 token\n", myname, lineno, input_file_name, s);
     done(1);
 }
tokenized_start (char * s)
Definition at line 178 of file error.c.
References done(), input_file_name, lineno, and myname.
Referenced by declare_tokens().
 {
      fprintf(stderr, "%s: e - line %d of \"%s\", the start symbol %s cannot be \
 declared to be a token\n", myname, lineno, input_file_name, s);
      done(1);
 }
undefined_goal (char * s)
Definition at line 318 of file error.c.
References done(), and myname.
Referenced by check_symbols().
 {
     fprintf(stderr, "%s: e - the start symbol %s is undefined\n", myname, s);
     done(1);
 }
undefined_symbol_warning (char * s)
Definition at line 326 of file error.c.
References myname.
Referenced by check_symbols().
 {
     fprintf(stderr, "%s: w - the symbol %s is undefined\n", myname, s);
 }
unexpected_EOF ()
Definition at line 42 of file error.c.
References done(), input_file_name, lineno, and myname.
Referenced by advance_to_start(), copy_ident(), declare_start(), declare_tokens(), declare_types(), get_tag(), and read_declarations().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", unexpected end-of-file\n",
             myname, lineno, input_file_name);
     done(1);
 }
unknown_rhs (int i)
Definition at line 302 of file error.c.
References done(), input_file_name, lineno, and myname.
Referenced by copy_action().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", $%d is untyped\n",
             myname, lineno, input_file_name, i);
     done(1);
 }
unterminated_action (int a_lineno, char * a_line, char * a_cptr)
Definition at line 251 of file error.c.
References done(), input_file_name, myname, and print_pos().
Referenced by copy_action().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", unterminated action\n",
             myname, a_lineno, input_file_name);
     print_pos(a_line, a_cptr);
     done(1);
 }
unterminated_comment (int c_lineno, char * c_line, char * c_cptr)
Definition at line 89 of file error.c.
References done(), input_file_name, myname, and print_pos().
Referenced by copy_action(), copy_text(), copy_union(), and skip_comment().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", unmatched /*\n",
             myname, c_lineno, input_file_name);
     print_pos(c_line, c_cptr);
     done(1);
 }
unterminated_string (int s_lineno, char * s_line, char * s_cptr)
Definition at line 101 of file error.c.
References done(), input_file_name, myname, and print_pos().
Referenced by copy_action(), copy_text(), copy_union(), and get_literal().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", unterminated string\n",
             myname, s_lineno, input_file_name);
     print_pos(s_line, s_cptr);
     done(1);
 }
unterminated_text (int t_lineno, char * t_line, char * t_cptr)
Definition at line 113 of file error.c.
References done(), input_file_name, myname, and print_pos().
Referenced by copy_text().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", unmatched %%{\n",
             myname, t_lineno, input_file_name);
     print_pos(t_line, t_cptr);
     done(1);
 }
unterminated_union (int u_lineno, char * u_line, char * u_cptr)
Definition at line 125 of file error.c.
References done(), input_file_name, myname, and print_pos().
Referenced by copy_union().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", unterminated %%union \
 declaration\n", myname, u_lineno, input_file_name);
     print_pos(u_line, u_cptr);
     done(1);
 }
untyped_lhs ()
Definition at line 284 of file error.c.
References done(), input_file_name, lineno, and myname.
Referenced by copy_action().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", $$ is untyped\n",
             myname, lineno, input_file_name);
     done(1);
 }
untyped_rhs (int i, char * s)
Definition at line 292 of file error.c.
References done(), input_file_name, lineno, and myname.
Referenced by copy_action().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", $%d (%s) is untyped\n",
             myname, lineno, input_file_name, i, s);
     done(1);
 }
used_reserved (char * s)
Definition at line 169 of file error.c.
References done(), input_file_name, lineno, and myname.
Referenced by get_name().
 {
     fprintf(stderr, "%s: e - line %d of \"%s\", illegal use of reserved symbol \
 %s\n", myname, lineno, input_file_name, s);
     done(1);
 }