Berkeley YACC: byacc/symtab.c File Reference
symtab.c File Reference
#include "defs.h"
Macros
#define TABLE_SIZE 1024
Functions
int hash (char *name)
bucket * make_bucket (char *name)
bucket * lookup (char *name)
create_symbol_table ()
free_symbol_table ()
free_symbols ()
Variables
bucket ** symbol_table
bucket * first_symbol
bucket * last_symbol
Macro Definition Documentation
#define TABLE_SIZE 1024
Definition at line 7 of file symtab.c.
Referenced by create_symbol_table(), and hash().
Function Documentation
create_symbol_table ()
Definition at line 83 of file symtab.c.
References bucket::class, hash(), bucket::index, make_bucket(), MALLOC, no_space(), TABLE_SIZE, and TERM.
Referenced by reader().
 {
     register int i;
     register bucket *bp;
     symbol_table = (bucket **) MALLOC(TABLE_SIZE*sizeof(bucket *));
     if (symbol_table == 0) no_space();
     for (i = 0; i < TABLE_SIZE; i++)
         symbol_table[i] = 0;
     bp = make_bucket("error");
     bp->index = 1;
     bp->class = TERM;
     first_symbol = bp;
     last_symbol = bp;
     symbol_table[hash("error")] = bp;
 }
free_symbol_table ()
Definition at line 103 of file symtab.c.
References FREE.
Referenced by reader().
 {
     FREE(symbol_table);
     symbol_table = 0;
 }
free_symbols ()
Definition at line 110 of file symtab.c.
References FREE, and bucket::next.
Referenced by reader().
 {
     register bucket *p, *q;
     for (p = first_symbol; p; p = q)
     {
         q = p->next;
         FREE(p);
     }
 }
int hash (char * name)
Definition at line 16 of file symtab.c.
References TABLE_SIZE.
Referenced by create_symbol_table(), and lookup().
 {
     register char *s;
     register int c, k;
     assert(name && *name);
     s = name;
     k = *s;
     while (c = *++s)
         k = (31*k + c) & (TABLE_SIZE - 1);
     return (k);
 }
bucket* lookup (char * name)
Definition at line 60 of file symtab.c.
References hash(), bucket::link, make_bucket(), bucket::name, and bucket::next.
 {
     register bucket *bp, **bpp;
     bpp = symbol_table + hash(name);
     bp = *bpp;
     while (bp)
     {
         if (strcmp(name, bp->name) == 0) return (bp);
         bpp = &bp->link;
         bp = *bpp;
     }
     *bpp = bp = make_bucket(name);
     last_symbol->next = bp;
     last_symbol = bp;
     return (bp);
 }
bucket* make_bucket (char * name)
Definition at line 33 of file symtab.c.
References bucket::assoc, bucket::index, bucket::link, MALLOC, bucket::name, bucket::next, no_space(), bucket::prec, strcpy(), bucket::tag, TOKEN, UNDEFINED, UNKNOWN, and bucket::value.
Referenced by create_symbol_table(), and lookup().
 {
     register bucket *bp;
     assert(name);
     bp = (bucket *) MALLOC(sizeof(bucket));
     if (bp == 0) no_space();
     bp->link = 0;
     bp->next = 0;
     bp->name = MALLOC(strlen(name) + 1);
     if (bp->name == 0) no_space();
     bp->tag = 0;
     bp->value = UNDEFINED;
     bp->index = 0;
     bp->prec = 0;
     bp-> class = UNKNOWN;
     bp->assoc = TOKEN;
     if (bp->name == 0) no_space();
     strcpy(bp->name, name);
     return (bp);
 }
Variable Documentation
bucket* first_symbol
Definition at line 11 of file symtab.c.
Referenced by check_symbols(), pack_names(), and pack_symbols().
bucket* last_symbol
Definition at line 12 of file symtab.c.
Referenced by insert_empty_rule().
bucket** symbol_table
Definition at line 10 of file symtab.c.